# Generated by Django 3.2.8 on 2021-10-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspirationifierApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageUrl',
            field=models.CharField(max_length=100000),
        ),
    ]
